spring:
  datasource:
    url: jdbc:h2:mem:onlinestore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none  # Отключаем автоматическое создание схемы Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      platform: h2
      schema-locations:  # Явно указываем порядок выполнения schema.sql
        - classpath*:schema.sql
      data-locations:    # Явно указываем порядок выполнения data.sql
        - classpath*:data.sql